### ISSUE TITLE
Puma config missing

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#1494]
This is broken in staging:

```
/usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/lib/puma/dsl.rb:20:in `read': No such file or directory @ rb_sysopen - config/puma (Errno::ENOENT)
        from /usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/lib/puma/dsl.rb:20:in `_load_from'
        from /usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/lib/puma/dsl.rb:9:in `block in load'
        from /usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/lib/puma/dsl.rb:8:in `tap'
        from /usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/lib/puma/dsl.rb:8:in `load'
        from /usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/lib/puma/configuration.rb:57:in `load'
        from /usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/lib/puma/cli.rb:543:in `parse_options'
        from /usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/lib/puma/cli.rb:189:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/puma-2.15.3/bin/puma:10:in `<top (required)>'
        from /usr/local/bin/puma:23:in `load'
```

**Comment by astopy** [comment]
Fixed by #1495
