### ISSUE TITLE
random Error 500, internal server error

### ISSUE THREAD

**Issue by alianos-** [zooniverse/Panoptes#475]
Hi, 
I am not sure what happens. I do a view request, it works. I repeat the request, error 500. From then on it alternates between 200 and 500 per request. I don't have all the "view" calls implemented, but listing all usergroups, listing all users and viewing the details of one usergroup,  ~~are all part of the same cycle. So if the listing all usergroups succeeds, any of the other calls will fail, the next will succeed and so on~~ all behave the same. I have list all projects as well but that always succeeds (then again, I have no projects).

Here is panoptes's log. If I can help you figure it out let me know what you need.

```
panoptes_1  | Started GET "/api/groups/1" for 192.168.1.97 at 2015-02-01 17:59:53 +0000
panoptes_1  | Processing by Api::V1::GroupsController#show as JSON_API
panoptes_1  |   Parameters: {"id"=>"1"}
panoptes_1  |   Doorkeeper::AccessToken Load (1.0ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens"  WHERE "oauth_access_tokens"."token" = '28320935bdd8d71fad6351786b8d4644002f078195f9fe5c5b3c6a8073238482'  ORDER BY "oauth_access_tokens"."id" ASC LIMIT 1
panoptes_1  |   User Load (2.0ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 1 LIMIT 1
panoptes_1  |   UserGroup Load (1.0ms)  SELECT  "user_groups".* FROM "user_groups"  WHERE "user_groups"."id" = 1 LIMIT 1
panoptes_1  |   UserGroup Load (1.0ms)  SELECT  "user_groups".* FROM "user_groups" LEFT OUTER JOIN (SELECT "memberships"."roles" AS roles, "memberships"."user_group_id", "memberships"."user_id" FROM "memberships"  WHERE "memberships"."user_id" = 1 AND "memberships"."state" = 0) roles_query ON "roles_query"."user_group_id" = "user_groups"."id" WHERE ((("roles_query"."roles" IS NOT NULL AND "roles_query"."roles" && '{group_admin,project_editor,collection_editor,group_member}') OR "user_groups"."private" = 'f')) AND "user_groups"."id" IN ('1') LIMIT 20 OFFSET 0
panoptes_1  |   OwnerName Load (1.0ms)  SELECT  "owner_names".* FROM "owner_names"  WHERE "owner_names"."resource_id" = 1 AND "owner_names"."resource_type" = 'UserGroup' LIMIT 1
panoptes_1  |    (1.0ms)  SELECT "memberships"."id" FROM "memberships"  WHERE "memberships"."user_group_id" = 1
panoptes_1  |    (1.0ms)  SELECT "users"."id" FROM "users" INNER JOIN "memberships" ON "users"."id" = "memberships"."user_id" WHERE "memberships"."user_group_id" = 1
panoptes_1  |    (0.0ms)  SELECT "projects"."id" FROM "projects"  WHERE "projects"."owner_id" = 1 AND "projects"."owner_type" = 'UserGroup'
panoptes_1  |    (1.0ms)  SELECT "collections"."id" FROM "collections"  WHERE "collections"."owner_id" = 1 AND "collections"."owner_type" = 'UserGroup'
panoptes_1  |    (1.0ms)  SELECT COUNT(DISTINCT "user_groups"."id") FROM "user_groups" LEFT OUTER JOIN (SELECT "memberships"."roles" AS roles, "memberships"."user_group_id", "memberships"."user_id" FROM "memberships"  WHERE "memberships"."user_id" = 1 AND "memberships"."state" = 0) roles_query ON "roles_query"."user_group_id" = "user_groups"."id" WHERE ((("roles_query"."roles" IS NOT NULL AND "roles_query"."roles" && '{group_admin,project_editor,collection_editor,group_member}') OR "user_groups"."private" = 'f')) AND "user_groups"."id" IN ('1')
panoptes_1  | Completed 500 Internal Server Error in 58ms
panoptes_1  | 
panoptes_1  | AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".):
panoptes_1  |   lib/json_api_controller/showable_resource.rb:5:in `show'
panoptes_1  |   app/middleware/catch_api_json_parse_errors.rb:8:in `call'
panoptes_1  |   app/middleware/reject_patch_requests.rb:8:in `call'
panoptes_1  | 
panoptes_1  | 
panoptes_1  |   Rendered /usr/local/lib/ruby/gems/shared/gems/actionpack-4.1.7/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.0ms)
panoptes_1  |   Rendered /usr/local/lib/ruby/gems/shared/gems/actionpack-4.1.7/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.0ms)
panoptes_1  |   Rendered /usr/local/lib/ruby/gems/shared/gems/actionpack-4.1.7/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (2.0ms)
panoptes_1  |   Rendered /usr/local/lib/ruby/gems/shared/gems/actionpack-4.1.7/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (32.0ms)
```

**Comment by alianos-** [comment]
In addition, projects behave the same now that there are projects to retrieve.

**Comment by camallen** [comment]
See #476, sounds like old server code issue that has been fixed.

**Comment by alianos-** [comment]
Yes, seems solved as well. Thanks.
