### ISSUE TITLE
Cellect server communication via fig / docker in dev mode

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#511]
Linked to: 492 (the last part not the first).

Seems Cellect client from panoptes cannot reach the cellect server when running locally in dev mode via fig. Production setup doesn't have this problem.

``` ruby
cellect_params = { workflow_id: '1', group_id: nil, limit: 5, host: host, user_id: 1 } 
=> {:workflow_id=>"1", :group_id=>nil, :limit=>5, :host=>"10.0.1.200", :user_id=>1}
[11] pry(main)> Cellect::Client.connection.get_subjects(**cellect_params)
E, [2015-02-07T12:39:30.970000 #410] ERROR -- : Actor crashed!
Java::JavaNet::ConnectException: Connection refused
	sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	sun.nio.ch.SocketChannelImpl.finishConnect(sun/nio/ch/SocketChannelImpl.java:739)
	java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
	RUBY.initialize(/usr/local/lib/ruby/gems/shared/gems/celluloid-io-0.16.0.pre/lib/celluloid/io/tcp_socket.rb:92)
	RUBY.open(/usr/local/lib/ruby/gems/shared/gems/celluloid-io-0.16.0.pre/lib/celluloid/io/tcp_socket.rb:16)
	RUBY.perform(/usr/local/lib/ruby/gems/shared/gems/http-0.7.1/lib/http/client.rb:54)
	RUBY.request(/usr/local/lib/ruby/gems/shared/gems/http-0.7.1/lib/http/client.rb:32)
	RUBY.request(/usr/local/lib/ruby/gems/shared/gems/http-0.7.1/lib/http/chainable.rb:72)
	RUBY.get(/usr/local/lib/ruby/gems/shared/gems/http-0.7.1/lib/http/chainable.rb:16)
	RUBY.send_http(/usr/local/lib/ruby/gems/shared/gems/cellect-client-0.0.9/lib/cellect/client/connection.rb:53)
	RUBY.get_subjects(/usr/local/lib/ruby/gems/shared/gems/cellect-client-0.0.9/lib/cellect/client/connection.rb:36)
	org.jruby.RubyKernel.public_send(org/jruby/RubyKernel.java:1958)
	Celluloid::Call.dispatch(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26)
	Celluloid::Call.dispatch(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26)
	Celluloid::SyncCall.dispatch(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:63)
	Celluloid::SyncCall.dispatch(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:63)
	Celluloid::Cell.invoke(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:60)
	Celluloid::Cell.invoke(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:60)
	Celluloid::Cell.task(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71)
	Celluloid::Cell.task(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71)
	Celluloid::Actor.task(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362)
	Celluloid::Actor.task(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362)
	Celluloid::Task.initialize(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55)
	Celluloid::Task.initialize(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55)
	Celluloid::Task.initialize(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:47)
	Celluloid::Task.initialize(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:47)
	Celluloid::TaskFiber.create(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_fiber.rb:15)
	Celluloid::TaskFiber.create(/usr/local/lib/ruby/gems/shared/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_fiber.rb:15)
	java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1145)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:615)
	java.lang.Thread.run(java/lang/Thread.java:745)
```
ping works from the running docker panoptes docker container
```bash
root@7239cf294b50:/rails_app# ping 10.0.1.200
PING 10.0.1.200 (10.0.1.200) 56(84) bytes of data.
64 bytes from 10.0.1.200: icmp_seq=1 ttl=64 time=0.046 ms
64 bytes from 10.0.1.200: icmp_seq=2 ttl=64 time=0.040 ms
^C
```
Telnet works ok though
```
root@7239cf294b50:/rails_app# telnet 10.0.1.200 9292
Trying 10.0.1.200...
Connected to 10.0.1.200.
Escape character is '^]'.
^]
```

**Comment by edpaget** [comment]
This is because I failed the expose the port in the Dockerfile: https://github.com/zooniverse/cellect_panoptes/blob/master/Dockerfile I will push a fix shortly.

**Comment by camallen** [comment]
Looks like we need to specify puma to run on port 80 too. Perhaps we should just use a config file as per [original cellect repo](https://github.com/zooniverse/Cellect/blob/master/config/puma.rb) and then tell puma to use it [here](https://github.com/zooniverse/cellect_panoptes/blob/master/start#L38) specify `puma -C config/puma.rb`

**Comment by edpaget** [comment]
I'm going to pass the bind and the thread configuration an argument to puma. It looked like there were only 3 declared options in that config file, and I'd prefer it log to stdout rather than to a log file.

**Comment by edpaget** [comment]
closed via 987abf3697096062aa300dbba5e5a5d5a2f7f4ab

**Comment by alianos-** [comment]
Excuse my noobism but what do I have to do to fix it? I have the latest version (downloaded 3-4 hours ago), it still happens.

**Comment by edpaget** [comment]
@alianos- run `fig pull cellect`. It will download the latest docker image.

**Comment by camallen** [comment]
Seems there are some zookeeper and db default config issues when the underlying YAML configs are missing. I'm going to fix these and PR them.

**Comment by camallen** [comment]
linked to https://github.com/zooniverse/cellect_panoptes/pull/5

this took longer than it should have, connection_pool could have played a bit nicer!

**Comment by camallen** [comment]
@alianos- can you run `fig pull cellect` again, then retry the latest code (git pull the latest) and the subjects via cellect? 

It'd be nice to know it's working in the wild.

**Comment by alianos-** [comment]
Hi Cambell. Thanks. I will probably do so tomorrow or Friday and let you 
know what happened. I am working part time for the project which why I 
disappear at times.

**Comment by alianos-** [comment]
I am not sure if I should be doing something else. I just did `fig pull cellect` and then `fig up`. I am afraid I still get an error.

```
Started GET "/api/subjects?sort=cellect&workflow_id=1&subject_set_id=1" for 192.168.1.80 at 2015-02-13 21:31:11 +0000
Processing by Api::V1::SubjectsController#index as JSON_API
  Parameters: {"sort"=>"cellect", "workflow_id"=>"1", "subject_set_id"=>"1"}
  Doorkeeper::AccessToken Load (1.0ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens"  WHERE "oauth_access_tokens"."token" = '2668153bbefeef42527e87ee13111c1839ac3fa13e9fcc27abb4b1a8841528b0'  ORDER BY "oauth_access_tokens"."id" ASC LIMIT 1
  User Load (1.0ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 1 LIMIT 1
Completed 500 Internal Server Error in 267ms

Cellect::Client::CellectServerError (Server Responded 500):
  lib/subject_selector.rb:30:in `cellect_subjects'
  lib/subject_selector.rb:13:in `create_response'
  app/controllers/api/v1/subjects_controller.rb:12:in `index'
  app/middleware/catch_api_json_parse_errors.rb:8:in `call'
  app/middleware/reject_patch_requests.rb:8:in `call'


  Rendered /usr/local/lib/ruby/gems/shared/gems/actionpack-4.1.9/lib/action_dispatch/middleware/templates/rescues/_source.erb (17.0ms)
  Rendered /usr/local/lib/ruby/gems/shared/gems/actionpack-4.1.9/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (7.0ms)
  Rendered /usr/local/lib/ruby/gems/shared/gems/actionpack-4.1.9/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (3.0ms)
  Rendered /usr/local/lib/ruby/gems/shared/gems/actionpack-4.1.9/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (62.0ms)
```

**Comment by edpaget** [comment]
We're sorting out some database format issues at the moment. You make need to FIG_RAKE=on rake db:drop db:create db:migrate.

**Comment by alianos-** [comment]
Different error

```
Started GET "/api/subjects?sort=cellect&workflow_id=1&subject_set_id=1" for 192.168.1.80 at 2015-02-14 00:10:10 +0000
Processing by Api::V1::SubjectsController#index as JSON_API
  Parameters: {"sort"=>"cellect", "workflow_id"=>"1", "subject_set_id"=>"1"}
  Doorkeeper::AccessToken Load (1.0ms)  SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens"  WHERE "oauth_access_tokens"."token" = '3c9f0592b78213da14832190167896555de1eb9ea553a5cbb06a61a80695da57'  ORDER BY "oauth_access_tokens"."id" ASC LIMIT 1
  User Load (1.0ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 1 LIMIT 1
Completed 500 Internal Server Error in 3064ms

Java::JavaNet::NoRouteToHostException (No route to host):
  sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
  sun.nio.ch.SocketChannelImpl.finishConnect(sun/nio/ch/SocketChannelImpl.java:739)
  java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
  RUBY.initialize(celluloid-io (0.16.0.pre) lib/celluloid/io/tcp_socket.rb:92)
  RUBY.open(celluloid-io (0.16.0.pre) lib/celluloid/io/tcp_socket.rb:16)
  RUBY.perform(http (0.7.1) lib/http/client.rb:54)
  RUBY.request(http (0.7.1) lib/http/client.rb:32)
  RUBY.request(http (0.7.1) lib/http/chainable.rb:72)
  RUBY.get(http (0.7.1) lib/http/chainable.rb:16)
  RUBY.send_http(cellect-client (0.0.9) lib/cellect/client/connection.rb:53)
  RUBY.get_subjects(cellect-client (0.0.9) lib/cellect/client/connection.rb:36)
  org.jruby.RubyKernel.public_send(org/jruby/RubyKernel.java:1958)
  Celluloid::Call.dispatch(celluloid (0.16.0.pre) lib/celluloid/calls.rb:26)
  Celluloid::Call.dispatch(celluloid (0.16.0.pre) lib/celluloid/calls.rb:26)
  Celluloid::SyncCall.dispatch(celluloid (0.16.0.pre) lib/celluloid/calls.rb:63)
  Celluloid::SyncCall.dispatch(celluloid (0.16.0.pre) lib/celluloid/calls.rb:63)
  Celluloid::Cell.invoke(celluloid (0.16.0.pre) lib/celluloid/cell.rb:60)
  Celluloid::Cell.invoke(celluloid (0.16.0.pre) lib/celluloid/cell.rb:60)
  Celluloid::Cell.task(celluloid (0.16.0.pre) lib/celluloid/cell.rb:71)
  Celluloid::Cell.task(celluloid (0.16.0.pre) lib/celluloid/cell.rb:71)
  Celluloid::Actor.task(celluloid (0.16.0.pre) lib/celluloid/actor.rb:362)
  Celluloid::Actor.task(celluloid (0.16.0.pre) lib/celluloid/actor.rb:362)
  Celluloid::Task.initialize(celluloid (0.16.0.pre) lib/celluloid/tasks.rb:55)
  Celluloid::Task.initialize(celluloid (0.16.0.pre) lib/celluloid/tasks.rb:55)
  Celluloid::Task.initialize(celluloid (0.16.0.pre) lib/celluloid/tasks.rb:47)
  Celluloid::Task.initialize(celluloid (0.16.0.pre) lib/celluloid/tasks.rb:47)
  Celluloid::TaskFiber.create(celluloid (0.16.0.pre) lib/celluloid/tasks/task_fiber.rb:15)
  Celluloid::TaskFiber.create(celluloid (0.16.0.pre) lib/celluloid/tasks/task_fiber.rb:15)
  java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1145)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:615)
  java.lang.Thread.run(java/lang/Thread.java:745)


  Rendered /usr/local/lib/ruby/gems/shared/gems/actionpack-4.1.9/lib/action_dispatch/middleware/templates/rescues/_source.erb (1.0ms)
  Rendered /usr/local/lib/ruby/gems/shared/gems/actionpack-4.1.9/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.0ms)
  Rendered /usr/local/lib/ruby/gems/shared/gems/actionpack-4.1.9/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (18.0ms)
  Rendered /usr/local/lib/ruby/gems/shared/gems/actionpack-4.1.9/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (54.0ms)
```

**Comment by camallen** [comment]
Did you restart the services via `fig stop` and `fig start`? Do you have project and workflow data in the db?

**Comment by alianos-** [comment]
I dont use fig stop because I see a live log (presumably because I run in dev mode). I stop with ctrl+C which I believe does the same as fig stop.

**Comment by camallen** [comment]
`Ctrl + C` stops the containers. Did you then run `fig up` and try the cellect server again? The error looks like the cellect client can't talk to the cellect server. What does the output of this command look like `fig logs cellect`?

**Comment by alianos-** [comment]
I am not sure I fully understand the difference, but in any case I did try fig stop and fig up and tried everything again, same result.

the output of the log is 

```
Attaching to panoptes_cellect_1
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/cellect-server-0.1.1/lib/cellect/server/adapters/default.rb:38:in `load_workflows'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/cellect-server-0.1.1/lib/cellect/server/workflow.rb:10:in `[]'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/cellect-server-0.1.1/lib/cellect/server/api/helpers.rb:6:in `workflow'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/cellect-server-0.1.1/lib/cellect/server/api/sets.rb:6:in `block in <class:Sets>'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:47:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:47:in `block in generate_api_method'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:247:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:247:in `run'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:195:in `block in call!'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:24:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:24:in `call!'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:18:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/error.rb:27:in `block in call!'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/error.rb:26:in `catch'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/error.rb:26:in `call!'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:18:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:196:in `call!'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:184:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/api.rb:102:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/api.rb:33:in `call!'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/api.rb:29:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/rack_patch.rb:13:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/configuration.rb:82:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/server.rb:507:in `handle_request'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/server.rb:375:in `process_client'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/server.rb:262:in `block in run'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
cellect_1 | 2015-02-16 11:50:10 +0000: Rack app error: #<PG::ConnectionBad: FATAL:  database "cellect" does not exist
cellect_1 | >
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/pg-0.18.1/lib/pg.rb:45:in `initialize'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/pg-0.18.1/lib/pg.rb:45:in `new'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/pg-0.18.1/lib/pg.rb:45:in `connect'
cellect_1 | /cellect_panoptes/lib/cellect/server/adapters/panoptes.rb:10:in `block in initialize'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.1/lib/connection_pool/timed_stack.rb:186:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.1/lib/connection_pool/timed_stack.rb:186:in `try_create'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.1/lib/connection_pool/timed_stack.rb:81:in `block (2 levels) in pop'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.1/lib/connection_pool/timed_stack.rb:77:in `loop'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.1/lib/connection_pool/timed_stack.rb:77:in `block in pop'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.1/lib/connection_pool/timed_stack.rb:76:in `synchronize'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.1/lib/connection_pool/timed_stack.rb:76:in `pop'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.1/lib/connection_pool.rb:78:in `checkout'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.1.1/lib/connection_pool.rb:60:in `with'
cellect_1 | /cellect_panoptes/lib/cellect/server/adapters/panoptes.rb:69:in `with_pg'
cellect_1 | /cellect_panoptes/lib/cellect/server/adapters/panoptes.rb:15:in `workflow_list'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/cellect-server-0.1.1/lib/cellect/server/adapters/default.rb:38:in `load_workflows'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/cellect-server-0.1.1/lib/cellect/server/workflow.rb:10:in `[]'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/cellect-server-0.1.1/lib/cellect/server/api/helpers.rb:6:in `workflow'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/cellect-server-0.1.1/lib/cellect/server/api/sets.rb:6:in `block in <class:Sets>'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:47:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:47:in `block in generate_api_method'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:247:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:247:in `run'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:195:in `block in call!'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:24:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:24:in `call!'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:18:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/error.rb:27:in `block in call!'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/error.rb:26:in `catch'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/error.rb:26:in `call!'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:18:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:196:in `call!'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/endpoint.rb:184:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/api.rb:102:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/api.rb:33:in `call!'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/grape-0.10.1/lib/grape/api.rb:29:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/rack_patch.rb:13:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/configuration.rb:82:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/server.rb:507:in `handle_request'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/server.rb:375:in `process_client'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/server.rb:262:in `block in run'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
cellect_1 | /usr/local/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by camallen** [comment]
Yeah - the cellect server is looking for the wrong db. 

That looks like i've forgotten to update fig.yml properly (we use configuration files in the cellect docker image to config our setup).Can you add `DB="panoptes_development"` to fig.yml [here](https://github.com/zooniverse/Panoptes/blob/a0e22a7068b14c3a0c32f063c09d82b8718379ac/fig.yml#L4)? 

Once done, stop and restart the fig server and try again?

**Comment by alianos-** [comment]
Yeap, that did it :)

It is not working properly though, it is always retrieving all subjects regardless of the subject set I provide. Shall I open a new issue?

**Comment by camallen** [comment]
Yes please. Also include the url you're using to perform subject selection via cellect.
